server:
  port: 8080
spring:
  application:
    name: risk-engine
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/kyc}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
logging:
  level:
    org.hibernate.SQL: warn
management:
  endpoints:
    web:
      exposure:
        include: health,info
