server:
  port: 8080
spring:
  application:
    name: risk-engine
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/kyc}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  liquibase:
    enabled: true
    change-log: classpath:db/liquibase/master.xml
    clear-checksums: true
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
logging:
  level:
    org.hibernate.SQL: warn
management:
  endpoints:
    web:
      exposure:
        include: health,info


app:
  exchanges:
    document: ${DOCUMENT_EXCHANGE:x.document}
    risk: ${RISK_EXCHANGE:x.risk}
  rk:
    decisionUpdated: ${RISK_RK_DECISION_UPDATED:decision.updated}
  queues:
    risk:
      ocrCompleted: ${Q_RISK_DOCUMENT_OCR_COMPLETED:q.risk.document.ocr.completed}
      biometricCompleted: ${Q_RISK_BIOMETRIC_COMPLETED:q.risk.biometric.completed}