server:
  port: 8080
spring:
  application:
    name: onboarding-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/kyc}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  liquibase:
    enabled: true
    change-log: classpath:db/liquibase/master.xml
    clear-checksums: true
logging:
  level:
    org.hibernate.SQL: warn
    liquibase: info
    bw.co.btc.kyc.onboarding: DEBUG
    org.springframework.amqp: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info

minio:
  endpoint: ${MINIO_ENDPOINT:http://minio:9000}
  accessKey: ${MINIO_ACCESS_KEY:minioadmin}
  secretKey: ${MINIO_SECRET_KEY:minioadmin123}
  bucket: ${MINIO_BUCKET:kyc-objects}
  presignTtlSeconds: ${MINIO_PRESIGN_TTL:300}


app:
  queues:
    document:
      metadataSaved: ${Q_ONBOARDING_DOCUMENT_METADATA_SAVED:q.onboarding.document.metadata.saved}
      ocrCompleted:  ${Q_ONBOARDING_DOCUMENT_OCR_COMPLETED:q.onboarding.document.ocr.completed}
    risk:
      decisionUpdated: ${Q_ONBOARDING_RISK_DECISION_UPDATED:q.onboarding.risk.decision.updated}
    onboarding:
      biometricMetadataSaved: ${Q_ONBOARDING_BIOMETRIC_METADATA_SAVED:q.onboarding.biometric.metadata.saved}
      biometricCompleted: ${Q_ONBOARDING_BIOMETRIC_COMPLETED:q.onboarding.biometric.completed}