server:
  port: 8080
spring:
  application:
    name: onboarding-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/kyc}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
logging:
  level:
    org.hibernate.SQL: warn
management:
  endpoints:
    web:
      exposure:
        include: health,info

minio:
  endpoint: ${MINIO_ENDPOINT:http://minio:9000}
  publicEndpoint: ${MINIO_PUBLIC_ENDPOINT:http://localhost:9000}
  accessKey: ${MINIO_ACCESS_KEY:minioadmin}
  secretKey: ${MINIO_SECRET_KEY:minioadmin123}
  bucket: ${MINIO_BUCKET:kyc-objects}
  presignTtlSeconds: ${MINIO_PRESIGN_TTL:300}
