server:
  port: 8080
spring:
  application:
    name: document-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/kyc}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  liquibase:
    enabled: true
    change-log: classpath:db/liquibase/master.xml
    clear-checksums: true
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

app:
  document:
    exchange: ${DOCUMENT_EXCHANGE:x.document}
    rk:
      metadataSaved: ${DOCUMENT_RK_METADATA_SAVED:document.metadata.saved}
      ocrCompleted:  ${DOCUMENT_RK_OCR_COMPLETED:document.ocr.completed}
  storage:
    defaultBucket: ${DEFAULT_BUCKET:kyc-objects}

logging:
  level:
    org.hibernate.SQL: warn
management:
  endpoints:
    web:
      exposure:
        include: health,info

