server:
  port: 8000

spring:
  application:
    name: gateway-service

management:
  endpoints:
    web:
      exposure:
        include: health,info

routes:
  onboarding: http://onboarding-service:8080
  document: http://document-service:8080
  biometrics: http://biometrics-service:8080

clients:
  onboarding: http://onboarding-service:8080

security:
  apiKey:
    header: X-API-Key
  injectHeaders: true
