server:
  port: 8080

spring:
  application:
    name: kyc-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        # Adds request/response ids to logs
        - name: DedupeResponseHeader
          args:
            name: Access-Control-Expose-Headers
            strategy: RETAIN_FIRST
      routes:
        - id: onboarding
          uri: ${ONBOARDING_URL:http://onboarding:8080}
          predicates:
            - Path=/api/onboarding/**
          filters:
            - StripPrefix=2
            - name: LoggingFilter
            - name: ApiKeyFilter
              args:
                required: false
                whitelist:
                  - /health
                  - /v1/sessions


        - id: documents
          uri: ${DOCUMENT_URL:http://document:8080}
          predicates:
            - Path=/api/documents/**
          filters:
            - StripPrefix=2
            - name: LoggingFilter
            - name: ApiKeyFilter
              args:
                headerName: X-API-Key
                tenantHeader: X-Tenant-Id

        - id: biometric
          uri: ${BIOMETRIC_URL:http://biometric:8080}
          predicates:
            - Path=/api/biometric/**
          filters:
            - StripPrefix=2
            - name: LoggingFilter
            - name: ApiKeyFilter
              args:
                headerName: X-API-Key
                tenantHeader: X-Tenant-Id

        - id: risk
          uri: ${RISK_URL:http://risk-engine:8080}
          predicates:
            - Path=/api/risk/**
          filters:
            - StripPrefix=2
            - name: LoggingFilter
            - name: ApiKeyFilter
              args:
                headerName: X-API-Key
                tenantHeader: X-Tenant-Id

  codec:
    max-in-memory-size: 10MB

# CORS (adjust for your frontend origin)
app:
  cors:
    allowed-origins: "*"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"

tenant:
  resolve:
    base: http://onboarding-service:8080
    path: /internal/tenants/resolve

logging:
  level:
    root: INFO
    bw.co.btc.kyc.gateway: DEBUG
    org.springframework.cloud.gateway: INFO
    bw.co.btc.kyc.gateway.client: DEBUG

