openapi: 3.1.0
info: { title: Biometrics API, version: 0.1.0 }
servers: [{ url: http://localhost:8004 }]
paths:
  /public/v1/sessions/{id}/selfie:
    post:
      summary: Intake selfie/liveness
      parameters: [{ name: id, in: path, required: true, schema: { type: string } }]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                selfieImageUrl: { type: string }
                livenessVideoUrl: { type: string }
      responses:
        "202": { description: accepted, content: { application/json: { schema: { type: object, properties: { accepted: { type: boolean }, correlationId: { type: string } } } } } }
