openapi: 3.1.0
info: { title: Document API, version: 0.1.0 }
servers: [{ url: http://localhost:8003 }]
paths:
  /public/v1/sessions/{id}/documents:
    post:
      summary: Intake documents
      parameters: [{ name: id, in: path, required: true, schema: { type: string } }]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [idType, idNumber]
              properties:
                idType: { type: string, enum: [OMANG, PASSPORT, DRIVERS_LICENSE] }
                idNumber: { type: string }
                frontImageUrl: { type: string }
                backImageUrl: { type: string }
      responses:
        "202": { description: accepted, content: { application/json: { schema: { type: object, properties: { accepted: { type: boolean }, correlationId: { type: string } } } } } }
