openapi: 3.1.0
info: { title: Risk Engine API, version: 0.1.0 }
servers: [{ url: http://localhost:8005 }]
paths:
  /internal/v1/decide/{sessionId}:
    post:
      summary: Compute a decision for a session
      parameters: [{ name: sessionId, in: path, required: true, schema: { type: string } }]
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessionId: { type: string }
                  status: { type: string, enum: [PENDING, AUTO_APPROVED, AUTO_REJECTED, REVIEW] }
                  reasons: { type: array, items: { type: string } }
